### ISSUE TITLE
デフォルト以外の項目名の変換について

### ISSUE THREAD

**Issue by microrelief** [icoxfog417/kintoneDotNET#34]
このたびKintoneDotNetを使用させていただき、社内Kintoneとの連携をおこなうアプリをC#にて作成いたしました。ありがとうございます。

開発環境でのテストは無事に完了し、いざ本番環境での使用のため本番環境のフィールドコードを確認したところ、ほぼデフォルトのまま（つまり日本語）となっており、またすでに多くの内外システムがそのまま連携してしまっているため、フィールドコードを半角文字に変更することが困難なことが判明したしました。

ConvertDictionaryをオーバーライドすることで、デフォルト項目の名称変更に対応できるという記述を見つけ、デフォルト以外の項目についても変換可能なのではないか？と考えいろいろとテストしているのですが、具体的にどのようにすべきかわからず、どうしてもうまくいきません。

■ためしたこと
AbskintoneModelを継承したクラスのなかにConvertDictionaryをオーバーライドしたプロパティを作成してみました。
ConvertDictionaryの定義をみたところ、直上に定義されたリストのフィールドをGetおよびSetしている内容だったため、このフィールドのリストもそのまま定義しました。
リストの中に変換したい内容を記述し、動作させたのですが予想通りうまくいきません。「ConvertDictionaryをオーバーライドする」という方法そのものを勘違いしている可能性が大きいとはおもうのですが、いろいろ調べてもどうしてもわからす、恥をしのんでこちらに書き込みをさせていただきました。

やはり、そもそもKintoneDotNetではデフォルト以外の項目の変換を行うことは難しいのでしょうか？
ご教示いただけますと幸いです。

--
class TestModel : AbskintoneModel
{
	--（省略）--

        private List<NameConvertor> _convertDictionary = new List<NameConvertor>()
        {
	　　NameConvertor.Create("$id", "record_id", NameConvertor.Direction.Read),
　　　　　　NameConvertor.Create("レコード", "record_id", NameConvertor.Direction.Send),
			--（省略）--
            NameConvertor.Create("フィールド名", "FieldName")　// ←ここに追加しました。
        };

        protected override List<NameConvertor> ConvertDictionary
        { 
            get
            {
                return _convertDictionary;
            }
            set
            {
                _convertDictionary = value;
            }
        }
}

**Comment by microrelief** [comment]
解決いたしましたのでご報告です。
これが最善手かどうかは不明ですが、問題なく動いています。
もっとよい方法があるようでしたら、教えて下さい。
KintoneDotNET すばらしいです。ありがとうございます。
お騒がせいたしました。

--
class TestModel : AbskintoneModel
{
    pblic TestModel()
    {
        base.ConvertDictionary = _convertDictionary;
    }

    private List<NameConvertor> _convertDictionary = new List<NameConvertor>()
    {
	NameConvertor.Create("フィールド名", "FieldName"),
    };
}

**Comment by microrelief** [comment]
度々すみません。訂正です。
上記ですと、読み込むことはできるようですが、書き込みができません。
残念です。

**Comment by microrelief** [comment]
isUploadの設定はtrueで問題ありません。NameConvertor.Directionのパラメータもつけたみましたが、書き込むことだけが出来ないようです。Kintone側のフィールドコードを半角にすれば、読み込み、書き込みともに可能です。全角文字にするとUpdateおよびSaveともに機能していないようです。何が足りないのだろう？

**Comment by microrelief** [comment]
■これまでに判明したこと。

_convertDictionaryへの上記方法での追加で

データの取得：２バイト文字のフィールドコードでも変換が行われ無事に処理されます。
データの登録：TestModel.Update(list); で、以下の例外が発生します。

>内部例外 1:
>AggregateException: 1 つ以上のエラーが発生しました。
>
>内部例外 2:
>kintoneException: 指定されたフィールド（record_id）が見つかりません。

_convertDictionaryリストに、オリジナルからコピーした

>NameConvertor.Create("$id", "record_id", NameConvertor.Direction.Read),

を追加すると例外はおきませんが、フィールドのアップデートは無視されます。

いろいろ試しているのですが、うまくいきません。やはりこのような使い方はできないのでしょうか？なにか情報をお持ちの方がいらっしゃいましたら教えて下さい。
何卒よろしくお願いいたします。

**Comment by icoxfog417** [comment]
フィールド名日本語は、少なくとも開発時想定をしていなかったです(日本語フィールド名だとプログラム上困難な処理があったため(どこかは忘れてしまいましたが・・・))。
私の方でもちょっと見てみます。

**Comment by microrelief** [comment]
お忙しいところありがとうございます！
KintoneDotNET作っていただきありがとうございます。
そうですか、、やはり日本語フィールド名は想定外だったのですね。教えていただきありがとうございます。
Kintoneもせめてデフォルトを半角にしてくれていたらよかったのにな、と思ってしまいました。いろいろお手数ですがよろしくお願いいたします。

**Comment by microrelief** [comment]
今回はやむをえず接続クラスを自作いたしました。
大変勉強になりました。ありがとうございました。
